language: cpp
compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libsdl-image1.2-dev
            - libsdl-dev
            - libsdl-net1.2
            - libsdl-net1.2-dev

    - os: osx
      osx_image: xcode10

script:
  - mkdir build && cd build
  - cmake ..
  - make
