language: cpp

dist: xenial

addons:
  apt:
    packages:
      - g++-8.3
      - cmake
      - libsdl-image1.2-dev
      - libsdl-dev
      - libsdl-net1.2
      - libsdl-net1.2-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make
